# Generated by Django 6.0.3 on 2026-05-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visit_notas_phototype_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('programada', 'Programado'), ('en_camino', 'Inicio'), ('llegada', 'Sitio'), ('trabajando', 'Servicios'), ('completada', 'Completado'), ('cancelada', 'Cancelado')], default='programada', max_length=16),
        ),
        migrations.AlterField(
            model_name='visittrackingpoint',
            name='event',
            field=models.CharField(choices=[('salida', 'Salida'), ('llegada', 'Llegada'), ('inicio', 'Inicio de trabajos'), ('cierre', 'Cierre de trabajos'), ('finalizado', 'Finalizado')], max_length=16),
        ),
    ]
