# Generated by Django 6.0.3 on 2026-05-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_tracking_finalizado_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitphoto',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('programada', 'Programado'), ('en_camino', 'Inicio'), ('llegada', 'Sitio'), ('trabajando', 'Servicio'), ('completada', 'Completado'), ('cancelada', 'Cancelado')], default='programada', max_length=16),
        ),
    ]
