# Generated by Django 6.0.5 on 2026-05-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_finalizando_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittrackingpoint',
            name='event',
            field=models.CharField(choices=[('salida', 'Salida'), ('llegada', 'Llegada'), ('inicio', 'Inicio de trabajos'), ('cierre', 'Cierre de Servicio'), ('finalizado', 'Finalizado')], max_length=16),
        ),
    ]
