# Generated by Django 6.0.5 on 2026-05-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('manager', 'Coordinator'), ('super_manager', 'Manager'), ('viewer', 'Solo lectura')], default='technician', max_length=16),
        ),
    ]
