# Generated by Django 6.0.3 on 2026-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='imei',
        ),
        migrations.AddField(
            model_name='userdevice',
            name='android_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
