# Generated by Django 6.0.3 on 2026-05-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userdevice_imei_userdevice_android_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='sim_serial',
        ),
    ]
