# Generated by Django 6.0.5 on 2026-05-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_status_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('manager', 'Coordinador'), ('super_manager', 'Manager'), ('viewer', 'Vista')], default='technician', max_length=16),
        ),
    ]
