# Generated by Django 6.0.5 on 2026-05-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='company',
            field=models.CharField(choices=[('wom', 'WOM'), ('pti', 'PTI'), ('default', 'Default (PTI)')], default='default', max_length=16, unique=True),
        ),
    ]
