# Generated by Django 6.0.5 on 2026-05-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_company_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_url',
            field=models.URLField(blank=True, help_text='(opcional) URL del logo SVG/PNG'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='name',
            field=models.CharField(help_text='Nombre visible de la empresa', max_length=64),
        ),
    ]
