# Generated by Django 6.0.3 on 2026-05-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='operator_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
