# Generated by Django 6.0.3 on 2026-05-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_add_operator_code_region_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='address',
        ),
    ]
