# Generated by Django 6.0.3 on 2026-05-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='region',
        ),
        migrations.AlterField(
            model_name='site',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
