# Generated by Django 6.0.5 on 2026-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_remove_region_height_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
